### ISSUE TITLE
Receiving secretOrPrivateKey must have a value upon login

### ISSUE THREAD

**Issue by Stef-Lan** [edwardcdev/apollobank#4]
After creating an account and attempting to login I am receiving the following error:
secretOrPrivateKey must have a value
Any idea why?

**Comment by edwardcdev** [comment]
Create .env file in your application /server folder with this content (as you see the format is key=value)
...
NODE_ENV=development
FRONT_APP_URL=http://localhost:3000
DATABASE_URL=postgres://postgres:postgres@localhost:5432/apollobank
REFRESH_TOKEN_SECRET=sd84eycsfp77ehdqw22w8f5igah9ty6l0s4x
ACCESS_TOKEN_SECRET=8v6ycio835bwgcksdx0vkzukk18y948w3dd9
PORT=4000
...

**Comment by Stef-Lan** [comment]
Thanks a lot, that worked!
